name: whatsapp
description: A Whatsapp Clone
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^4.1.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.5.2
  country_picker: ^2.0.20
  device_preview: ^1.1.0
  emoji_picker_flutter: ^1.5.4
  enough_giphy_flutter: ^0.4.0
  file_picker: ^5.3.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_bubble: ^2.0.2
  flutter_chat_types: ^3.6.1
  flutter_contacts: ^1.1.6
  flutter_link_previewer: ^3.2.1
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.10.2
  flutter_riverpod: ^2.3.5
  flutter_sound: ^9.2.13
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  story_view: ^0.14.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
