name: whatsapp
description: A Whatsapp Clone
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.6.0
  bloc: ^8.1.1
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.5.2
  country_picker: ^2.0.27
  device_preview: ^1.1.0
  emoji_picker_flutter: ^4.4.0
  enough_giphy_flutter: ^0.4.0
  file_picker: ^11.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_chat_bubble: ^2.0.2
  flutter_chat_types: ^3.6.1
  flutter_contacts: ^1.1.6
  flutter_link_previewer: ^4.2.0
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.10.2
  flutter_riverpod: ^3.3.1
  flutter_sound: ^9.30.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  story_view: ^0.14.0
  swipe_to: ^1.0.2
  url_launcher: ^6.3.2
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
