name: whatsapp
description: A Whatsapp Clone
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.3
  country_picker: ^2.0.20
  device_preview: ^1.1.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_chat_bubble: ^2.0.2
  flutter_contacts: ^1.1.6
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.10.2
  flutter_riverpod: ^2.3.5
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
